### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by YashuC** [WebDevSimplified/YouTube-Video-Title-View-Updater#2]
I am getting some errors when I am trying to run node server.js and i chnaged nothing in the code s and i am pretty sure i did everything right but just when i apply the command i am getting this:

var redirectUrl = credentials.installed.redirect_uris[0];
^

TypeError: Cannot read property '0' of undefined
at authorize (E:\Desktop\YoutubeVideoUpdater\server.js:31:56)
at processClientSecrets (E:\Desktop\YoutubeVideoUpdater\server.js:18:3)
at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

Here is the code: [server.zip](https://github.com/WebDevSimplified/YouTube-Video-Title-View-Updater/files/5480801/server.zip)

**Comment by RobinJesba** [comment]
Add to client_secret.json
```
"redirect_uris": [
            "urn:ietf:wg:oauth:2.0:oob",
            "http://localhost"
        ]
``` 
**client_secret.json**
```
{
    "installed": {
        "client_id": "xxxx",
        "project_id": "xxxx",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "xxxx",
        "redirect_uris": [
            "urn:ietf:wg:oauth:2.0:oob",
            "http://localhost"
        ]
    }
}
```
